package com.example.nadia.lietner_box.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CARD".
 */
public class card {

    private Long id;
    private Integer cardCel;
    private Long groupId;
    private String question;
    private String answer;
    private java.util.Date LDate;

    public card() {
    }

    public card(Long id) {
        this.id = id;
    }

    public card(Long id, Integer cardCel, Long groupId, String question, String answer, java.util.Date LDate) {
        this.id = id;
        this.cardCel = cardCel;
        this.groupId = groupId;
        this.question = question;
        this.answer = answer;
        this.LDate = LDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCardCel() {
        return cardCel;
    }

    public void setCardCel(Integer cardCel) {
        this.cardCel = cardCel;
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public java.util.Date getLDate() {
        return LDate;
    }

    public void setLDate(java.util.Date LDate) {
        this.LDate = LDate;
    }

}
