package com.example.nadia.lietner_box.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUP".
 */
public class group {

    private Long id;
    private String GroupName;
    private java.util.Date date;
    private String type;//download OR
    private Long parentId;

    public group() {
    }

    public group(Long id) {
        this.id = id;
    }

    public group(Long id, String GroupName, java.util.Date date, String type, Long parentId) {
        this.id = id;
        this.GroupName = GroupName;
        this.date = date;
        this.type = type;
        this.parentId = parentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return GroupName;
    }

    public void setGroupName(String GroupName) {
        this.GroupName = GroupName;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

}
